# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

eigenMapMatInv <- function(A, n_cores) {
    .Call(`_fastGEE_eigenMapMatInv`, A, n_cores)
}

eigenMapMatMult <- function(A, B, n_cores) {
    .Call(`_fastGEE_eigenMapMatMult`, A, B, n_cores)
}

eigenMapMatTrans <- function(A, n_cores) {
    .Call(`_fastGEE_eigenMapMatTrans`, A, n_cores)
}

